"""A deliberately small numerical compiler: odd LUT/PWL rewriting + word-length search.

The mathematical frontend is specific to normalize_sensor.m. This is not a MATLAB
parser. The generated arithmetic has the SAME widths/rounding as evaluate().
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np

from .problem import Contract, Golden, analytic, metrics, partitions, write_json


@dataclass(frozen=True)
class Design:
    architecture: str = "pwl"
    segments_log2: int = 6
    fraction_bits: int = 16
    rounding: str = "nearest"

    def __post_init__(self) -> None:
        if self.architecture not in {"pwl", "lut"} or self.rounding not in {"nearest", "floor"}:
            raise ValueError("Unknown architecture or rounding")
        if not 3 <= self.segments_log2 <= 11 or not 12 <= self.fraction_bits <= 20:
            raise ValueError("Unsupported design size")

    @property
    def name(self) -> str:
        return f"{self.architecture}_s{1 << self.segments_log2}_f{self.fraction_bits}_{self.rounding}"

    @property
    def shift(self) -> int:
        return 11 - self.segments_log2

    @property
    def table(self) -> np.ndarray:
        # Knot generation is offline floating-point work, not synthesized math.
        x = np.arange((1 << self.segments_log2) + 1) * (1 << self.shift)
        return np.floor(analytic(x) * (1 << self.fraction_bits) + 0.5).astype(np.int64)

    @property
    def widths(self) -> dict:
        table = self.table
        return {"magnitude": 12, "index": self.segments_log2 + 1,
                "table": max(1, int(table.max()).bit_length()),
                "delta": max(1, int(np.diff(table).max()).bit_length()),
                "offset": self.shift + 1, "work": self.fraction_bits + 13}

    def evaluate(self, adc: np.ndarray) -> np.ndarray:
        adc = np.asarray(adc, dtype=np.int64)
        if np.any((adc < -2048) | (adc > 2047)):
            raise ValueError("ADC code out of range")
        magnitude = np.abs(adc)  # Widen before negating -2048.
        n, s, f = 1 << self.segments_log2, self.shift, self.fraction_bits
        table = self.table
        if self.architecture == "lut":
            idx = (magnitude + ((1 << (s-1)) if s else 0)) >> s
            value = table[np.minimum(idx, n)]
        else:
            idx = np.minimum(magnitude >> s, n-1)
            offset = magnitude - (idx << s)
            # Endpoint offset is a full segment, so it requires s+1 bits.
            product = (table[idx+1] - table[idx]) * offset
            value = table[idx] + ((product + ((1 << (s-1)) if s and self.rounding == "nearest" else 0)) >> s)
        if f >= 14:
            d = f-14
            value = (value + ((1 << (d-1)) if d and self.rounding == "nearest" else 0)) >> d
        else:
            value = value << (14-f)
        if np.any(value > 32767):
            raise OverflowError("Output narrowing would overflow")
        return np.where(adc < 0, -value, value).astype(np.int64)

    def resource_proxy(self) -> int:
        """Search heuristic only. NOT FPGA LUT counts, area, timing or power."""
        w, n = self.widths, 1 << self.segments_log2
        return (n+1)*w["table"] + (n*w["delta"] + w["delta"]*(self.shift+1)*4 if self.architecture == "pwl" else 0)

    def range_report(self) -> dict:
        table = self.table
        delta, span = int(np.diff(table).max()), 1 << self.shift
        return {"domain": [-2048, 2047], "abs_after_signed_extension": [0, 2048],
                "knot_range": [0, int(table.max())], "delta_range": [0, delta],
                "offset_range": [0, span], "product_upper_bound": delta*span,
                "work_bits": self.widths["work"],
                "product_fits": delta*span < (1 << self.widths["work"]),
                "note": "Analytic intermediate bound for this template; output error is tested separately"}

    def dslx(self) -> str:
        w, s, f, n = self.widths, self.shift, self.fraction_bits, 1 << self.segments_log2
        table, work = self.table, w["work"]
        u = f"uN[{work}]"
        lines = ["// Generated by structured numerical search. Input s12 / 2048; output s16 / 16384.",
                 "pub fn main(x: s12) -> s16 {",
                 "  let wide = x as s13;",
                 "  let mag = (if wide < s13:0 { -wide } else { wide }) as u12;"]
        literal = ", ".join(f"uN[{w['table']}]:{v}" for v in table)
        lines.append(f"  let knots = uN[{w['table']}][{n+1}]:[{literal}];")
        if self.architecture == "lut":
            bias = (1 << (s-1)) if s else 0
            lines += [f"  let idx = ((mag as u13 + u13:{bias}) >> u13:{s}) as u32;",
                      f"  let v = knots[idx] as {u};"]
        else:
            delta_literal = ", ".join(f"uN[{w['delta']}]:{v}" for v in np.diff(table))
            lines += [f"  let deltas = uN[{w['delta']}][{n}]:[{delta_literal}];",
                      f"  let raw_idx = (mag >> u12:{s}) as u32;",
                      f"  let idx = if raw_idx >= u32:{n} {{ u32:{n-1} }} else {{ raw_idx }};",
                      f"  let offset = (mag as {u}) - ((idx as {u}) << {u}:{s});",
                      f"  let product = (deltas[idx] as {u}) * offset;",
                      f"  let v = (knots[idx] as {u}) + ((product + {u}:{(1 << (s-1)) if s and self.rounding == 'nearest' else 0}) >> {u}:{s});"]
        if f >= 14:
            d = f-14
            lines.append(f"  let q = ((v + {u}:{(1 << (d-1)) if d and self.rounding == 'nearest' else 0}) >> {u}:{d}) as s16;")
        else:
            lines.append(f"  let q = (v << {u}:{14-f}) as s16;")
        lines += ["  if wide < s13:0 { -q } else { q }", "}"]
        return "\n".join(lines) + "\n"

    def verilog_fixture(self) -> str:
        """Independent HDL spelling for harness replay. Never described as XLS output."""
        s, f, n, w = self.shift, self.fraction_bits, 1 << self.segments_log2, self.widths
        table = self.table
        cases = "\n".join(f"      {i}: begin base = {int(table[i])}; delta = {int(table[min(i+1,n)]-table[i])}; end" for i in range(n+1))
        index = f"(mag + {1 << (s-1) if s else 0}) >> {s}" if self.architecture == "lut" else f"(mag == 2048) ? {n-1} : (mag >> {s})"
        value = "base" if self.architecture == "lut" else f"base + ((delta * offset + {(1 << (s-1)) if s and self.rounding == 'nearest' else 0}) >> {s})"
        d = f-14
        quantize = f"(value + {(1 << (d-1)) if d > 0 and self.rounding == 'nearest' else 0}) >> {d}" if d >= 0 else f"value << {-d}"
        return f'''// Handwritten-emitter replay fixture, NOT an Astra response and NOT XLS output.
module dut(input wire clk, input wire rst, input wire in_valid,
           input wire signed [11:0] x,
           output reg out_valid, output reg signed [15:0] y);
  reg signed [11:0] xr;
  reg vr;
  reg signed [12:0] wide;
  reg [11:0] mag;
  reg [11:0] idx;
  reg [{w['work']-1}:0] base, delta, offset, value, quantized;
  reg signed [15:0] result;
  always @* begin
    wide = {{xr[11], xr}};
    mag = wide < 0 ? -wide : wide;
    idx = {index};
    base = 0; delta = 0;
    case (idx)
{cases}
      default: begin base = 0; delta = 0; end
    endcase
    offset = mag - (idx << {s});
    value = {value};
    quantized = {quantize};
    result = xr < 0 ? -$signed(quantized[15:0]) : $signed(quantized[15:0]);
  end
  always @(posedge clk) begin
    if (rst) begin xr <= 0; vr <= 0; out_valid <= 0; y <= 0; end
    else begin xr <= x; vr <= in_valid; out_valid <= vr; y <= result; end
  end
endmodule
'''


def search(golden: Golden, contract: Contract, out: Path) -> list[dict]:
    golden.require_normalizer()
    out.mkdir(parents=True, exist_ok=True)
    dev, _ = partitions()
    records = []
    for architecture in ["pwl", "lut"]:
        for log in (range(3, 9) if architecture == "pwl" else range(7, 12)):
            for fraction in [12, 14, 16, 18]:
                for rounding in ["floor", "nearest"]:
                    design = Design(architecture, log, fraction, rounding)
                    records.append({"name": design.name, "design": asdict(design),
                                    "proxy_cost": design.resource_proxy(),
                                    "numeric": metrics(dev, design.evaluate(dev), golden, contract)})
    records.sort(key=lambda r: (not r["numeric"]["pass"], r["proxy_cost"], r["numeric"]["max_abs_error"]))
    feasible = [r for r in records if r["numeric"]["pass"]]
    if not feasible:
        raise RuntimeError("No numerically feasible candidate")
    chosen = feasible[:3]
    for architecture in ["pwl", "lut"]:
        extra = next((r for r in feasible if r["design"]["architecture"] == architecture), None)
        if extra and extra not in chosen:
            chosen.append(extra)
    for r in chosen:
        d = Design(**r["design"])
        folder = out / d.name
        folder.mkdir(exist_ok=True)
        (folder / "candidate.x").write_text(d.dslx())
        (folder / "fixture.sv").write_text(d.verilog_fixture())
        write_json(folder / "design.json", r)
        write_json(folder / "ranges.json", d.range_report())
    write_json(out / "search.json", {"status": "numerical_search_only", "golden": golden.provenance,
               "contract": contract.as_dict(), "tested_candidates": len(records), "feasible": len(feasible),
               "selected": [r["name"] for r in chosen], "records": records,
               "warning": "proxy_cost is not a measured FPGA resource count; no hardware success implied"})
    return chosen
